### PR TITLE
Add Jeremy's placeholder photo

### LINKED ISSUE #7: Add Jeremy's photo

### PR DESCRIPTION
**Pull request by jtooya**
closes #7

### CODE REVIEW

**Review by zienxu — COMMENTED** [review]
lgtm

**Review by zienxu — APPROVED** [review]
lgtm approve

**Review by SlothyCat — APPROVED** [review]
LGTM 😄

**Review by SlothyCat — CHANGES_REQUESTED** [review]
LGTM BUT LETS GO

**Review by SlothyCat — APPROVED** [review]
NOW CAN APPROVE

**Comment by kimberlytmq** [comment]
why all ur photos so boring one boooo

**Comment by SlothyCat** [comment]
> why all ur photos so boring one boooo

WAEEEEEEE

**Pull request merged**
