### PR TITLE
Fix Remark Error Message Typo

### PR DESCRIPTION
**Pull request by SlothyCat**

### CODE REVIEW

**Comment by kimberlytmq** [comment]
idk if this counts as making it more specific?
image

and also 1 to 200 characters already kinda says that cannot be 0 (blank)

**Review by kimberlytmq — CHANGES_REQUESTED** [review]
check comment

**Comment by SlothyCat** [comment]
> check comment

Hmm I have only removed a trailing whitespace for the file so I thought it could fall under the spelling/ grammar error part. But on second thought, I am not sure if this is counted as an enhancement.

**Review by kimberlytmq — APPROVED** [review]
OHH mb I thought u added the 'it cannot be blank' I saw wrong. lgtm!

**Pull request merged**
